name: Shell Commands

on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
  
    steps:
      - name: echo a string
        run: echo "Hello GitHub!!"
      - name: multi line
        run: |
          node -v
          npm -v